### PR TITLE
Remove Manifest.toml

### LINKED ISSUE #189: 17 Errors when test PowerModelsDistribution
Hello,

I try the test with pkg : test PowerModelsDistribution, and I have 17 errors.

Did it normal ?

Thank you for your work.

The results of the test 👍 

(v1.3) pkg> test PowerModelsDistribution
   Testing PowerModelsDistribution
 Resolving package versions...
 Installed Cbc ────────── v0.6.6
 Installed MathProgBase ─ v0.7.7
 Installed Ipopt ──────── v0.6.1
 Installed Juniper ────── v0.5.2
 Installed SCS ────────── v0.6.3
  Building Cbc ──→ `C:\Users\fd244075\.julia\packages\Cbc\vWzyC\deps\build.log`
  Building Ipopt → `C:\Users\fd244075\.julia\packages\Ipopt\ruIXY\deps\build.log`
  Building SCS ──→ `C:\Users\fd244075\.julia\packages\SCS\pHU71\deps\build.log`
    Status `C:\Users\fd244075\AppData\Local\Temp\jl_EI5td3\Manifest.toml`
  [6e4b80f9] BenchmarkTools v0.4.3
  [b99e7846] BinaryProvider v0.5.8
  [49dc2e85] Calculus v0.5.1
  [9961bab8] Cbc v0.6.6
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.2.0
  [864edb3b] DataStructures v0.17.6
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.1.0
  [8f5d6c58] EzXML v0.9.5
  [f6369f11] ForwardDiff v0.10.7
  [2030c09a] InfrastructureModels v0.3.2
  [b6b21f68] Ipopt v0.6.1
  [682c06a0] JSON v0.21.0
  [4076af6c] JuMP v0.20.1
  [2ddba703] Juniper v0.5.2
  [b8f27783] MathOptInterface v0.9.7
  [fdba3010] MathProgBase v0.7.7
  [f28f55f0] Memento v0.12.1
  [78c3b35d] Mocking v0.7.0
  [77ba4419] NaNMath v0.3.3
  [efe28fd5] OpenSpecFun_jll v0.5.3+1
  [bac558e1] OrderedCollections v1.1.0
  [69de0a69] Parsers v0.3.10
  [c36e90e8] PowerModels v0.13.0
  [d7431456] PowerModelsDistribution v0.6.0
  [c946c3f1] SCS v0.6.3
  [276daf66] SpecialFunctions v0.9.0
  [90137ffa] StaticArrays v0.12.1
  [cea106d9] Syslogs v0.3.0
  [f269a46b] TimeZones v0.10.3
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
[ Info: running matlab parser tests
[ Info: running opendss parser tests
[ Info: running misc data handling tests
[ Info: running power flow (pf) tests

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

[ Info: running optimal power flow (opf) tests
[ Info: running branch-flow optimal power flow (opf_bf) tests
5-bus independent radial identical sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:115
  Expression: result["termination_status"] == PMs.OPTIMAL
   Evaluated: ALMOST_OPTIMAL == OPTIMAL
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:115
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:112
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus independent radial identical sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:116
  Expression: isapprox(result["objective"], 55451.2; atol=2.0)
   Evaluated: isapprox(53935.65643887419, 55451.2; atol=2.0)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:116
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:112
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus independent radial different sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:123
  Expression: result["termination_status"] == PMs.OPTIMAL
   Evaluated: ALMOST_OPTIMAL == OPTIMAL
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:123
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:120
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus independent radial different sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:124
  Expression: isapprox(result["objective"], 56091.7; atol=2.0)
   Evaluated: isapprox(56050.074971081485, 56091.7; atol=2.0)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:124
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:120
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus independent radial different sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:126
  Expression: isapprox(((((result["solution"])["gen"])["1"])["qg"])[1], 0.2362121; atol=0.02)
   Evaluated: isapprox(0.07385876625990893, 0.2362121; atol=0.02)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:126
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:120
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus independent radial different sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:127
  Expression: isapprox(((((result["solution"])["gen"])["1"])["qg"])[2], -0.0219214; atol=0.02)
   Evaluated: isapprox(0.007403728015208866, -0.0219214; atol=0.02)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:127
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:120
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus independent radial different sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:128
  Expression: isapprox(((((result["solution"])["gen"])["1"])["qg"])[3], -0.0249553; atol=0.02)
   Evaluated: isapprox(0.006952859155090541, -0.0249553; atol=0.02)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:128
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:120
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:152
  Expression: result["termination_status"] == PMs.OPTIMAL
   Evaluated: ALMOST_OPTIMAL == OPTIMAL
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:152
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:153
  Expression: isapprox(result["objective"], 55434.8; atol=20.0)
   Evaluated: isapprox(53713.537748942916, 55434.8; atol=20.0)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:153
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:156
  Expression: isapprox(((((result["solution"])["gen"])["1"])["pg"])[c], 0.4; atol=0.001)
   Evaluated: isapprox(0.4530598508857477, 0.4; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:156
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:156
  Expression: isapprox(((((result["solution"])["gen"])["1"])["pg"])[c], 0.4; atol=0.001)
   Evaluated: isapprox(0.38635677538807967, 0.4; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:156
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:157
  Expression: isapprox(((((result["solution"])["bus"])["2"])["vm"])[c], 1.0862; atol=0.001)
   Evaluated: isapprox(1.0954637991631846, 1.0862; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:157
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:156
  Expression: isapprox(((((result["solution"])["gen"])["1"])["pg"])[c], 0.4; atol=0.001)
   Evaluated: isapprox(0.35127564022209523, 0.4; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:156
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial no shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:157
  Expression: isapprox(((((result["solution"])["bus"])["2"])["vm"])[c], 1.0862; atol=0.001)
   Evaluated: isapprox(1.1053815852289646, 1.0862; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:157
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:149
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:165
  Expression: result["termination_status"] == PMs.OPTIMAL
   Evaluated: ALMOST_OPTIMAL == OPTIMAL
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:165
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:162
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:166
  Expression: isapprox(result["objective"], 56075.9; atol=2.0)
   Evaluated: isapprox(56031.03663724942, 56075.9; atol=2.0)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:166
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:162
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:169
  Expression: isapprox(((((result["solution"])["gen"])["1"])["pg"])[c], 0.4; atol=0.001)
   Evaluated: isapprox(0.39768381800718183, 0.4; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:169
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:162
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:169
  Expression: isapprox(((((result["solution"])["gen"])["1"])["pg"])[c], 0.4; atol=0.001)
   Evaluated: isapprox(0.39732713018262555, 0.4; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:169
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:162
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
5-bus coupled radial shunt sdpubf opf_bf: Test Failed at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:169
  Expression: isapprox(((((result["solution"])["gen"])["1"])["pg"])[c], 0.4; atol=0.001)
   Evaluated: isapprox(0.39735544326964767, 0.4; atol=0.001)
Stacktrace:
 [1] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:169
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:162
 [4] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [5] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:111
 [6] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [7] top-level scope at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\opf_bf.jl:4
[ Info: running storage optimal power flow tests
[ Info: running debug (pdf) tests
[ Info: running multinetwork tests
[ Info: running transformer tests
[ Info: running load models tests
[ Info: running minimum load delta (mld) tests
┌ Warning: NLP couldn't be solved to optimality
└ @ Juniper C:\Users\fd244075\.julia\packages\Juniper\i4qvA\src\fpump.jl:389
[ Info: no explicit NLP constraints or objective provided using @NLconstraint or @NLobjective macros
┌ Warning: Cycle detected
└ @ Juniper C:\Users\fd244075\.julia\packages\Juniper\i4qvA\src\fpump.jl:374
Test Summary:                                               | Pass  Fail  Total
PowerModelsDistribution                                     |  760    19    779
  test matlab data parser                                   |   17           17
  test opendss parser                                       |  198          198
  test json parser                                          |    1            1
  test data handling functions                              |   19           19
  test pf                                                   |   90           90
  test pf_bf                                                |    4            4
  test opf                                                  |  136          136
  test distflow formulations                                |   34    19     53
    test linearised distflow opf_bf                         |   15           15
    test linearised distflow opf_bf in diagonal matrix form |    8            8
    test linearised distflow opf_bf in full matrix form     |    7            7
    test sdp distflow opf_bf                                |    4    19     23
      5-bus independent radial identical sdpubf opf_bf      |          2      2
      5-bus independent radial different sdpubf opf_bf      |          5      5
      5-bus independent meshed different sdpubf opf_bf      |    2            2
      5-bus coupled meshed infeasible sdpubf opf_bf         |    1            1
      5-bus coupled radial no shunt sdpubf opf_bf           |    1     7      8
      5-bus coupled radial shunt sdpubf opf_bf              |          5      5
  test storage opf                                          |   30           30
  test pbs                                                  |    8            8
  test multinetwork                                         |   62           62
  test transformer pf                                       |   36           36
  test loadmodels pf                                        |   79           79
  test mld                                                  |   46           46
ERROR: LoadError: Some tests did not pass: 760 passed, 19 failed, 0 errored, 0 broken.
in expression starting at C:\Users\fd244075\.julia\packages\PowerModelsDistribution\7gijI\test\runtests.jl:36
ERROR: Package PowerModelsDistribution errored during testing

### PR DESCRIPTION
**Pull request by ccoffrin**
Closes #189.

### CODE REVIEW

**Comment by ccoffrin** [comment]
@sanderclaeys, it looks like one case still has an issue with SCS v0.6.3?

**Comment by sanderclaeys** [comment]
@ccoffrin I could not reproduce the failing test, even though I am on SCS v0.6.3. I commented out the failing test, I do not known what else to try.

**Comment by frederikgeth** [comment]
@ccoffrin should we worry about these windows tests errorring?

**Comment by ccoffrin** [comment]
I would say no, having a look at the logs it seems to be false negative.

**Comment by ccoffrin** [comment]
I recomend merging this.

**Comment by frederikgeth** [comment]
done!

**Pull request merged**
